/*
 * The MIT License
 *
 * Copyright 2024 imarc.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package gui.formularios;

import aplicacion.Actividad;
import aplicacion.FachadaAplicacion;
import gui.modelos.ModeloListaActividades;

import java.util.List;

/**
 *
 * @author imarc
 */
public class VGesActividades extends javax.swing.JFrame {

    FachadaAplicacion fa;

    /**
     * Creates new form VGesActividades
     */
    public VGesActividades(FachadaAplicacion fa) {
        this.fa = fa;
        initComponents();
        ModeloListaActividades modelo = (ModeloListaActividades) jList1.getModel();

        listarActividades();
        
        txtNombreCategoriaExistente.setEditable(false);
        
        this.pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        txtNombreCategoriaExistente = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDescripcionCategoria = new javax.swing.JTextArea();
        txtTipoCategoriaExistente = new javax.swing.JTextField();
        btnModificarCategoria = new javax.swing.JButton();
        btnFulminar = new javax.swing.JButton();
        labelNombreCategoriaExistente = new javax.swing.JLabel();
        labelTipoCategoriaExistente = new javax.swing.JLabel();
        btnActualizarActividades = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Actividades");
        setModalExclusionType(java.awt.Dialog.ModalExclusionType.TOOLKIT_EXCLUDE);
        setType(java.awt.Window.Type.UTILITY);

        jList1.setModel(new ModeloListaActividades());
        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        txtNombreCategoriaExistente.setToolTipText("Nombre de la categoría");
        txtNombreCategoriaExistente.setName("txtNombreCategoria"); // NOI18N
        txtNombreCategoriaExistente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreCategoriaExistenteActionPerformed(evt);
            }
        });

        txtDescripcionCategoria.setColumns(20);
        txtDescripcionCategoria.setRows(5);
        jScrollPane2.setViewportView(txtDescripcionCategoria);

        txtTipoCategoriaExistente.setName("Tipo categoria"); // NOI18N

        btnModificarCategoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconoDisquete7070.png"))); // NOI18N
        btnModificarCategoria.setToolTipText("Modificar la categoría con los campos actuales");
        btnModificarCategoria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnModificarCategoriaMouseClicked(evt);
            }
        });

        btnFulminar.setText("FULMINAR");
        btnFulminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFulminarMouseClicked(evt);
            }
        });

        labelNombreCategoriaExistente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelNombreCategoriaExistente.setText("Nombre");
        labelNombreCategoriaExistente.setToolTipText("");
        labelNombreCategoriaExistente.setName("etiquetaNombreCategoria"); // NOI18N

        labelTipoCategoriaExistente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTipoCategoriaExistente.setText("Tipo");
        labelTipoCategoriaExistente.setToolTipText("");
        labelTipoCategoriaExistente.setName("etiquetaTipoCategoria"); // NOI18N

        btnActualizarActividades.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ouroborosAdecuado.png"))); // NOI18N
        btnActualizarActividades.setMaximumSize(new java.awt.Dimension(70, 78));
        btnActualizarActividades.setPreferredSize(new java.awt.Dimension(68, 70));
        btnActualizarActividades.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnActualizarActividadesMouseClicked(evt);
            }
        });

        jButton1.setText("Nueva");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jDesktopPane1.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(txtNombreCategoriaExistente, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jScrollPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(txtTipoCategoriaExistente, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(btnModificarCategoria, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(btnFulminar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(labelNombreCategoriaExistente, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(labelTipoCategoriaExistente, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(btnActualizarActividades, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                                .addComponent(btnFulminar))
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNombreCategoriaExistente, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                                    .addComponent(labelNombreCategoriaExistente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtTipoCategoriaExistente, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                                    .addComponent(labelTipoCategoriaExistente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 141, Short.MAX_VALUE))))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnActualizarActividades, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnModificarCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(8, Short.MAX_VALUE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addComponent(btnActualizarActividades, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 18, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                        .addComponent(labelNombreCategoriaExistente)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtNombreCategoriaExistente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(3, 3, 3))
                                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                        .addComponent(labelTipoCategoriaExistente)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtTipoCategoriaExistente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(18, 18, 18)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jDesktopPane1Layout.createSequentialGroup()
                                .addComponent(btnModificarCategoria)
                                .addGap(18, 18, 18)
                                .addComponent(btnFulminar))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(32, 32, 32))
        );

        txtNombreCategoriaExistente.getAccessibleContext().setAccessibleName("Nombre de la categoria");
        txtTipoCategoriaExistente.getAccessibleContext().setAccessibleName("Tipo de la categoria");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
       int indice = jList1.getSelectedIndex();
         ModeloListaActividades modelo = (ModeloListaActividades) jList1.getModel();
            Actividad actividad = modelo.getActividadAt(indice);
            txtNombreCategoriaExistente.setText(actividad.getNombre());
            txtTipoCategoriaExistente.setText(actividad.getTipo());
            txtDescripcionCategoria.setText(actividad.getDescripcion());
    }//GEN-LAST:event_jList1MouseClicked

    private void txtNombreCategoriaExistenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreCategoriaExistenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreCategoriaExistenteActionPerformed

    private void btnActualizarActividadesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizarActividadesMouseClicked
        this.listarActividades();
    }//GEN-LAST:event_btnActualizarActividadesMouseClicked

    private void btnFulminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFulminarMouseClicked
        ModeloListaActividades modelo = (ModeloListaActividades) jList1.getModel();
        int indice = jList1.getSelectedIndex();
        if (indice != -1) {
            Actividad actividad = modelo.getActividadAt(indice);
            fa.eliminarActividad(actividad);
            this.listarActividades();
        }
    }//GEN-LAST:event_btnFulminarMouseClicked

    private void btnModificarCategoriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModificarCategoriaMouseClicked
        if(jList1.getSelectedIndex() == -1)
        {
            fa.muestraExcepcion("Selecciona una actividad para modificarla");
        }
        else
        {
            if(txtNombreCategoriaExistente.getText().length()>20 || txtNombreCategoriaExistente.getText().isEmpty())
            {
                fa.muestraExcepcion("El nombre de la actividad debe tener entre 1 y 20 caracteres");
                return;
            }

            if(txtTipoCategoriaExistente.getText().length()>50 || txtTipoCategoriaExistente.getText().isEmpty())
            {
                fa.muestraExcepcion("El tipo de la actividad debe tener entre 1 y 50 caracteres");
                return;
            }

            if(txtDescripcionCategoria.getText().length()>500 || txtDescripcionCategoria.getText().isEmpty())
            {
                fa.muestraExcepcion("La descripción de la actividad debe tener entre 1 y 500 caracteres");
                return;
            }

            ModeloListaActividades modelo = (ModeloListaActividades) jList1.getModel();
            int indice = jList1.getSelectedIndex();
            Actividad actividad = modelo.getActividadAt(indice);
            fa.modificarActividad(actividad, txtNombreCategoriaExistente.getText(), txtDescripcionCategoria.getText(), txtTipoCategoriaExistente.getText());
            this.listarActividades();
        }
    }//GEN-LAST:event_btnModificarCategoriaMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        VCreacionActividad vca = new VCreacionActividad(fa);
        vca.setVisible(true);
        vca.pack();
    }//GEN-LAST:event_jButton1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarActividades;
    private javax.swing.JButton btnFulminar;
    private javax.swing.JButton btnModificarCategoria;
    private javax.swing.JButton jButton1;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelNombreCategoriaExistente;
    private javax.swing.JLabel labelTipoCategoriaExistente;
    private javax.swing.JTextArea txtDescripcionCategoria;
    private javax.swing.JTextField txtNombreCategoriaExistente;
    private javax.swing.JTextField txtTipoCategoriaExistente;
    // End of variables declaration//GEN-END:variables

    public void listarActividades() {
        ModeloListaActividades modelo = (ModeloListaActividades) jList1.getModel();
        List<Actividad> actividades = fa.consultarActividades();
        modelo.setFilas(actividades);
    }
}
