/*
 * The MIT License
 *
 * Copyright 2024 imarc.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package gui.formularios;

import aplicacion.*;
import gui.modelos.*;

import javax.swing.*;
import java.util.ArrayList;
import java.util.List;

/**
 * @author imarc
 */
public final class VGesGrupos extends JFrame {

    FachadaAplicacion fa;

    List<Cliente> arrayListIzqAlumnosNoEnGrupo = new ArrayList<>();
    List<Cliente> arrayListDchAlumnosSiEnGrupo = new ArrayList<>();
//    List<Cliente> arrayListAlumnosEliminar = new ArrayList<>();


    /**
     * Creates new form VGesGrupos
     */
    public VGesGrupos(FachadaAplicacion fa) {
        this.fa = fa;
        initComponents();

        txtID.setEditable(false);

        this.listarGrupos();
        this.listarProfesores();
        this.listarActividades();
        this.pack();
    }

    private void listarActividades() {
        ModeloListaActividades modelo = (ModeloListaActividades) jListActividades.getModel();
        modelo.setFilas(fa.consultarActividades());
    }


    private void listarGrupos() {
        ModeloListaGrupos modelo = (ModeloListaGrupos) jListaGrupos.getModel();
        modelo.setFilas(fa.obtenerGrupos());
    }

    // INI ALUMNOS EN GRUPO

    private void rellenarListasAlumnosVsGrupos(Grupo grupo) {


        List<Cliente> listAlumnosSiEnGrupo = fa.obtenerClientesGrupo(grupo);

//        this.arrayListDchAlumnosSiEnGrupo.clear();
//        this.arrayListDchAlumnosSiEnGrupo.addAll(listAlumnosSiEnGrupo);
        this.arrayListDchAlumnosSiEnGrupo = listAlumnosSiEnGrupo;

        ModeloListaCliente modeloListaDchAlumnosSiEnGrupo = (ModeloListaCliente) this.jListDchAlumnosSiEnGrupo.getModel();
        modeloListaDchAlumnosSiEnGrupo.setClientes(this.arrayListDchAlumnosSiEnGrupo);

        // --

        ModeloListaCliente modeloListaIzqAlumnosNoEnGrupo = (ModeloListaCliente) this.jListIzqAlumnosNoEnGrupo.getModel();

        List<Cliente> listAlumnosNoEnGrupo = fa.obtenerClientes();

        listAlumnosNoEnGrupo.removeAll(listAlumnosSiEnGrupo);

        this.arrayListIzqAlumnosNoEnGrupo = listAlumnosNoEnGrupo;

        modeloListaIzqAlumnosNoEnGrupo.setClientes(this.arrayListIzqAlumnosNoEnGrupo);

        if (modeloListaIzqAlumnosNoEnGrupo.getSize() == 0) {
            btnAnhadirAlumnoAlGrupo.setEnabled(false);
        } else {
            jListIzqAlumnosNoEnGrupo.setSelectedIndex(0);
        }

    }

    // FIN ALUMNOS EN GRUPO

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialogoAlumnosMatriculadosEnElGrupo = new javax.swing.JDialog();
        jDesktopPane2 = new javax.swing.JDesktopPane();
        jScrollPaneIzqAlumnosNoEnGrupo = new javax.swing.JScrollPane();
        jListIzqAlumnosNoEnGrupo = new javax.swing.JList<>();
        jScrollPaneDchAlumnosSiEnGrupo = new javax.swing.JScrollPane();
        jListDchAlumnosSiEnGrupo = new javax.swing.JList<>();
        btnAnhadirAlumnoAlGrupo = new javax.swing.JButton();
        btnEliminarAlumnoDelGrupo = new javax.swing.JButton();
        btnGuardarCambiosAlumnosEnGrupo = new javax.swing.JButton();
        jLabelIzqAlumnosNoDelGrupo = new javax.swing.JLabel();
        jLabelDchAlumnosSiDelGrupo = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        btnGrupoNuevo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListaGrupos = new javax.swing.JList<>();
        lblID = new javax.swing.JLabel();
        btnAlumnos = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        btnGuardarCambiosGrupos = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jScrollPane3 = new javax.swing.JScrollPane();
        jListProfesores = new javax.swing.JList<>();
        txtID = new javax.swing.JTextField();
        lblProfesoresMain = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListActividades = new javax.swing.JList<>();
        lblProfesoresMain2 = new javax.swing.JLabel();
        btnBorrarGrupo = new javax.swing.JButton();

        dialogoAlumnosMatriculadosEnElGrupo.setModalityType(java.awt.Dialog.ModalityType.TOOLKIT_MODAL);
        dialogoAlumnosMatriculadosEnElGrupo.setMinimumSize(new java.awt.Dimension(409, 309));

        jDesktopPane2.setMinimumSize(new java.awt.Dimension(409, 309));

        jListIzqAlumnosNoEnGrupo.setModel(new ModeloListaCliente());
        jScrollPaneIzqAlumnosNoEnGrupo.setViewportView(jListIzqAlumnosNoEnGrupo);

        jListDchAlumnosSiEnGrupo.setModel(new ModeloListaCliente());
        jScrollPaneDchAlumnosSiEnGrupo.setViewportView(jListDchAlumnosSiEnGrupo);

        btnAnhadirAlumnoAlGrupo.setText("Añadir =>");
        btnAnhadirAlumnoAlGrupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnhadirAlumnoAlGrupoActionPerformed(evt);
            }
        });

        btnEliminarAlumnoDelGrupo.setText("<= Eliminar");
        btnEliminarAlumnoDelGrupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarAlumnoDelGrupoActionPerformed(evt);
            }
        });

        btnGuardarCambiosAlumnosEnGrupo.setText("Guardar cambios");
        btnGuardarCambiosAlumnosEnGrupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarCambiosAlumnosEnGrupoActionPerformed(evt);
            }
        });

        jLabelIzqAlumnosNoDelGrupo.setText("Resto de alumnos");

        jLabelDchAlumnosSiDelGrupo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelDchAlumnosSiDelGrupo.setText("Alumnos del grupo");

        jDesktopPane2.setLayer(jScrollPaneIzqAlumnosNoEnGrupo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jScrollPaneDchAlumnosSiEnGrupo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(btnAnhadirAlumnoAlGrupo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(btnEliminarAlumnoDelGrupo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(btnGuardarCambiosAlumnosEnGrupo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jLabelIzqAlumnosNoDelGrupo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jLabelDchAlumnosSiDelGrupo, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane2Layout = new javax.swing.GroupLayout(jDesktopPane2);
        jDesktopPane2.setLayout(jDesktopPane2Layout);
        jDesktopPane2Layout.setHorizontalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelIzqAlumnosNoDelGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPaneIzqAlumnosNoEnGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnGuardarCambiosAlumnosEnGrupo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAnhadirAlumnoAlGrupo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEliminarAlumnoDelGrupo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPaneDchAlumnosSiEnGrupo, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                    .addComponent(jLabelDchAlumnosSiDelGrupo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(15, 15, 15))
        );
        jDesktopPane2Layout.setVerticalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane2Layout.createSequentialGroup()
                        .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelDchAlumnosSiDelGrupo)
                            .addComponent(jLabelIzqAlumnosNoDelGrupo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPaneIzqAlumnosNoEnGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane2Layout.createSequentialGroup()
                                .addComponent(jScrollPaneDchAlumnosSiEnGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane2Layout.createSequentialGroup()
                        .addComponent(btnAnhadirAlumnoAlGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminarAlumnoDelGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(btnGuardarCambiosAlumnosEnGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32))))
        );

        javax.swing.GroupLayout dialogoAlumnosMatriculadosEnElGrupoLayout = new javax.swing.GroupLayout(dialogoAlumnosMatriculadosEnElGrupo.getContentPane());
        dialogoAlumnosMatriculadosEnElGrupo.getContentPane().setLayout(dialogoAlumnosMatriculadosEnElGrupoLayout);
        dialogoAlumnosMatriculadosEnElGrupoLayout.setHorizontalGroup(
            dialogoAlumnosMatriculadosEnElGrupoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        dialogoAlumnosMatriculadosEnElGrupoLayout.setVerticalGroup(
            dialogoAlumnosMatriculadosEnElGrupoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnGrupoNuevo.setText("Nuevo Grupo");
        btnGrupoNuevo.setToolTipText("crear un grupo nuevo");
        btnGrupoNuevo.setName("Nuevo Grupo"); // NOI18N
        btnGrupoNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrupoNuevoActionPerformed(evt);
            }
        });

        jListaGrupos.setModel(new ModeloListaGrupos());
        jListaGrupos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListaGruposMouseClicked(evt);
            }
        });
        jListaGrupos.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListaGruposValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jListaGrupos);

        lblID.setText("ID:");

        btnAlumnos.setText("Alumnos del Grupo");
        btnAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarAlumnosMatriculadosEnElGrupoActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(153, 0, 0));
        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ouroborosAdecuado.png"))); // NOI18N
        jButton3.setEnabled(false);
        jButton3.setVisible(false);

        btnGuardarCambiosGrupos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconoDisquete7070.png"))); // NOI18N
        btnGuardarCambiosGrupos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarCambiosGruposActionPerformed(evt);
            }
        });

        jListProfesores.setModel(new ModeloListaProfesor());
        jScrollPane3.setViewportView(jListProfesores);

        lblProfesoresMain.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblProfesoresMain.setText("Profesor");

        jListActividades.setModel(new ModeloListaActividades());
        jScrollPane2.setViewportView(jListActividades);

        lblProfesoresMain2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblProfesoresMain2.setText("Actividad");

        btnBorrarGrupo.setText("Borrar Grupo");
        btnBorrarGrupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarGrupoActionPerformed(evt);
            }
        });

        jDesktopPane1.setLayer(btnGrupoNuevo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(lblID, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(btnAlumnos, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButton2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButton3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(btnGuardarCambiosGrupos, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(filler1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jScrollPane3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(txtID, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(lblProfesoresMain, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jScrollPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(lblProfesoresMain2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(btnBorrarGrupo, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(btnAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(btnGrupoNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblID)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBorrarGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblProfesoresMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(280, 280, 280)
                        .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblProfesoresMain2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton3)
                            .addComponent(jButton2)
                            .addComponent(btnGuardarCambiosGrupos))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addComponent(btnGrupoNuevo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblID)
                                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(btnBorrarGrupo)
                        .addGap(0, 91, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addComponent(jButton3)
                                .addGap(18, 18, 18)
                                .addComponent(btnGuardarCambiosGrupos))
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblProfesoresMain)
                                    .addComponent(lblProfesoresMain2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
                                    .addComponent(jScrollPane2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(34, 34, 34)
                        .addComponent(jButton2)
                        .addContainerGap())))
        );

        btnGrupoNuevo.getAccessibleContext().setAccessibleName("Nuevo grupo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jListaGruposValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListaGruposValueChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jListaGruposValueChanged

    private void jListaGruposMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListaGruposMouseClicked
        int selectedIndex = jListaGrupos.getSelectedIndex();
        if (selectedIndex == -1) {
            return;
        }
        ModeloListaGrupos modeloListaGrupos = (ModeloListaGrupos) jListaGrupos.getModel();
        txtID.setText(String.valueOf(modeloListaGrupos.getGrupoAt(selectedIndex).getIdGrupo()));
        jListActividades.setSelectedValue(modeloListaGrupos.getGrupoAt(selectedIndex).getActividad().getNombre(), true);
        jListProfesores.setSelectedValue(fa.obtenerProfesorGrupo(modeloListaGrupos.getGrupoAt(selectedIndex).getIdGrupo()).getNombre(), true);
        // arrayListAlumnosEliminar.clear();
        // arrayListAlumnosActualesGrupo.clear();
    }//GEN-LAST:event_jListaGruposMouseClicked

    private void btnGuardarCambiosGruposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        int selectedIndex = jListaGrupos.getSelectedIndex();
        if (selectedIndex == -1) {
            fa.muestraExcepcion("No se ha seleccionado ningún grupo");
            return;
        }

        ModeloListaGrupos modeloListaGrupos = (ModeloListaGrupos) jListaGrupos.getModel();
        ModeloListaActividades modeloActividades = (ModeloListaActividades) jListActividades.getModel();
        ModeloListaProfesor modeloProfesores = (ModeloListaProfesor) jListProfesores.getModel();
        Grupo grupo = modeloListaGrupos.getGrupoAt(selectedIndex);
        Actividad actividad = modeloActividades.getActividadAt(jListActividades.getSelectedIndex());
        Profesor profesor = modeloProfesores.getProfesorAt(jListProfesores.getSelectedIndex());

        fa.modificarGrupo(grupo, actividad, profesor);


    }//GEN-LAST:event_btnGuardarActionPerformed

    // INI ALUMNOS EN GRUPO

    private void btnMostrarAlumnosMatriculadosEnElGrupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarAlumnosMatriculadosEnElGrupoActionPerformed
//        arrayListAlumnosEliminar.isEmpty();

        int selectedIndex = jListaGrupos.getSelectedIndex();

        if (selectedIndex == -1) {
            fa.muestraExcepcion("No se ha seleccionado ningún grupo");
            return;
        }

//        this.rellenarListaIzqAlumnosNoEnGrupo(true);
//        this.rellenarListaDchAlumnosSiEnGrupo(true);


        ModeloListaGrupos modeloListaGrupos = (ModeloListaGrupos) this.jListaGrupos.getModel();

        Grupo grupo = modeloListaGrupos.getGrupoAt(selectedIndex);

        rellenarListasAlumnosVsGrupos(grupo);

        dialogoAlumnosMatriculadosEnElGrupo.pack();
        dialogoAlumnosMatriculadosEnElGrupo.setVisible(true);
    }//GEN-LAST:event_btnMostrarAlumnosMatriculadosEnElGrupoActionPerformed

    private void btnAnhadirAlumnoAlGrupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnhadirAlumnoAlGrupoActionPerformed
        // Voy a meter en mi arraylist de alumnos del grupo a los alumnos de la lista de alumnos participantes (listaAlumnosGrupo)

        int selectedIndexIzqAlumnosNoEnGrupo = jListIzqAlumnosNoEnGrupo.getSelectedIndex();
        if (selectedIndexIzqAlumnosNoEnGrupo == -1) {
            fa.muestraExcepcion("No se ha seleccionado ningún alumno del listado general de alumnos");
            return;
        }

        // --

        ModeloListaCliente modeloListaIzqAlumnosNoEnGrupo = (ModeloListaCliente) jListIzqAlumnosNoEnGrupo.getModel();
        ModeloListaCliente modeloListaDchAlumnosSiEnGrupo = (ModeloListaCliente) jListDchAlumnosSiEnGrupo.getModel();

//      if (!arrayListAlumnosActualesGrupo.contains(modeloListaIzqAlumnosNoEnGrupo.getClienteAt(selectedIndexIzqAlumnosNoEnGrupo))) {
//          arrayListAlumnosActualesGrupo.add(modeloListaIzqAlumnosNoEnGrupo.getClienteAt(selectedIndexIzqAlumnosNoEnGrupo));
        modeloListaDchAlumnosSiEnGrupo.nuevoElemento(modeloListaIzqAlumnosNoEnGrupo.getClienteAt(selectedIndexIzqAlumnosNoEnGrupo));
        modeloListaIzqAlumnosNoEnGrupo.borrarElemento(selectedIndexIzqAlumnosNoEnGrupo);
//      }

        if (modeloListaIzqAlumnosNoEnGrupo.getSize() == 0) {
            btnAnhadirAlumnoAlGrupo.setEnabled(false);
        } else {
            jListIzqAlumnosNoEnGrupo.setSelectedIndex(0);
        }

        // Y voy a actualizar la lista de alumnos del grupo
//      this.rellenarListaDchAlumnosSiEnGrupo(false);

        jListDchAlumnosSiEnGrupo.setSelectedIndex(modeloListaDchAlumnosSiEnGrupo.getSize() - 1);
        btnEliminarAlumnoDelGrupo.setEnabled(true);
    }//GEN-LAST:event_btnAnhadirAlumnoAlGrupoActionPerformed

    // --

    private void btnEliminarAlumnoDelGrupoActionPerformed(java.awt.event.ActionEvent evt) {

        int selectedIndexDchAlumnosSiEnGrupo = jListDchAlumnosSiEnGrupo.getSelectedIndex();
        if (selectedIndexDchAlumnosSiEnGrupo == -1) {
            fa.muestraExcepcion("No se ha seleccionado ningún alumno de entre los pertenecientes al grupo");
            return;
        }

        // --

        ModeloListaCliente modeloListaIzqAlumnosNoEnGrupo = (ModeloListaCliente) jListIzqAlumnosNoEnGrupo.getModel();
        ModeloListaCliente modeloListaDchAlumnosSiEnGrupo = (ModeloListaCliente) jListDchAlumnosSiEnGrupo.getModel();

//      arrayListAlumnosActualesGrupo.remove(modeloListaDchAlumnosSiEnGrupo.getClienteAt(selectedIndexDchAlumnosSiEnGrupo));
//        arrayListAlumnosEliminar.remove(modelo.getClienteAt(listaAlumnosTotales.getSelectedIndex()));

        modeloListaIzqAlumnosNoEnGrupo.nuevoElemento(modeloListaDchAlumnosSiEnGrupo.getClienteAt(selectedIndexDchAlumnosSiEnGrupo));
        modeloListaDchAlumnosSiEnGrupo.borrarElemento(selectedIndexDchAlumnosSiEnGrupo);

        if (modeloListaDchAlumnosSiEnGrupo.getSize() == 0) {
            btnEliminarAlumnoDelGrupo.setEnabled(false);
        } else {
            jListDchAlumnosSiEnGrupo.setSelectedIndex(0);
        }

        // Y voy a actualizar la lista de alumnos del grupo
//      this.rellenarListaDchAlumnosSiEnGrupo(false);


        jListIzqAlumnosNoEnGrupo.setSelectedIndex(modeloListaIzqAlumnosNoEnGrupo.getSize() - 1);
        btnAnhadirAlumnoAlGrupo.setEnabled(true);
    }

    private void btnGuardarCambiosAlumnosEnGrupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarCambiosAlumnosEnGrupoActionPerformed

        int selectedIndex = jListaGrupos.getSelectedIndex();
        if (selectedIndex == -1) {
            fa.muestraExcepcion("No se ha seleccionado ningún grupo");
            return;
        }

        ModeloListaGrupos modeloListaGrupos = (ModeloListaGrupos) this.jListaGrupos.getModel();

//        if (!this.arrayListAlumnosEliminar.isEmpty()) {
//            fa.eliminarAlumnosGrupo(modeloListaGrupos.getGrupoAt(selectedIndex), arrayListAlumnosEliminar);
//            fa.muestraMensaje("Alumnos eliminados correctamente");
//        }

        //if (!this.arrayListAlumnosActualesGrupo.isEmpty()) {

        fa.setAlumnosGrupo(modeloListaGrupos.getGrupoAt(selectedIndex), this.arrayListDchAlumnosSiEnGrupo);
        dialogoAlumnosMatriculadosEnElGrupo.dispose();
        fa.muestraMensaje("Alumnos añadidos correctamente");
        //}
    }//GEN-LAST:event_btnGuardarCambiosAlumnosEnGrupoActionPerformed

    private void btnGrupoNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrupoNuevoActionPerformed

        int selectedIndexProfesor = jListProfesores.getSelectedIndex();
        if (selectedIndexProfesor == -1) {
            fa.muestraExcepcion("No se ha seleccionado ningún profesor");
            return;
        }

        ModeloListaProfesor modeloProfesores = (ModeloListaProfesor) jListProfesores.getModel();
        Profesor profesor = modeloProfesores.getProfesorAt(jListProfesores.getSelectedIndex());

        // --

        int selectedIndexActividad = jListActividades.getSelectedIndex();
        if (selectedIndexActividad == -1) {
            fa.muestraExcepcion("No se ha seleccionado ninguna actividad");
            return;
        }

        ModeloListaActividades modeloActividades = (ModeloListaActividades) jListActividades.getModel();
        Actividad actividad = modeloActividades.getActividadAt(jListActividades.getSelectedIndex());

        // --

        fa.crearGrupo(actividad.getIdActividad(), Integer.parseInt(profesor.getIdUsuario()));

        fa.muestraMensaje("Nuevo grupo creado correctamente. Se le ha asociado al profesor " + profesor.getNombre() +
                " y a la a actividad " + actividad.getNombre() + ".");

        this.listarGrupos();
    }//GEN-LAST:event_btnGrupoNuevoActionPerformed

    private void btnBorrarGrupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarGrupoActionPerformed

        int selectedIndex = jListaGrupos.getSelectedIndex();

        if (selectedIndex == -1) {
            fa.muestraExcepcion("No se ha seleccionado ningún grupo");
            return;
        }

        // --

        ModeloListaGrupos modeloListaGrupos = (ModeloListaGrupos) this.jListaGrupos.getModel();

        Grupo grupo = modeloListaGrupos.getGrupoAt(selectedIndex);

        if (fa.grupoTieneSesiones(grupo)) {
            fa.muestraExcepcion("No se puede borrar un grupo que tiene sesiones asociadas.");
            return;
        }

        fa.borrarGrupo(grupo);

        fa.muestraMensaje("Se ha borrado correctamente el grupo número " + grupo.getIdGrupo() +".");

        this.listarGrupos();

    }//GEN-LAST:event_btnBorrarGrupoActionPerformed

    // INI ALUMNOS EN GRUPO


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlumnos;
    private javax.swing.JButton btnAnhadirAlumnoAlGrupo;
    private javax.swing.JButton btnBorrarGrupo;
    private javax.swing.JButton btnEliminarAlumnoDelGrupo;
    private javax.swing.JButton btnGrupoNuevo;
    private javax.swing.JButton btnGuardarCambiosAlumnosEnGrupo;
    private javax.swing.JButton btnGuardarCambiosGrupos;
    private javax.swing.JDialog dialogoAlumnosMatriculadosEnElGrupo;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JLabel jLabelDchAlumnosSiDelGrupo;
    private javax.swing.JLabel jLabelIzqAlumnosNoDelGrupo;
    private javax.swing.JList<String> jListActividades;
    private javax.swing.JList<String> jListDchAlumnosSiEnGrupo;
    private javax.swing.JList<String> jListIzqAlumnosNoEnGrupo;
    private javax.swing.JList<String> jListProfesores;
    private javax.swing.JList<String> jListaGrupos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPaneDchAlumnosSiEnGrupo;
    private javax.swing.JScrollPane jScrollPaneIzqAlumnosNoEnGrupo;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblProfesoresMain;
    private javax.swing.JLabel lblProfesoresMain2;
    private javax.swing.JTextField txtID;
    // End of variables declaration//GEN-END:variables

    void listarProfesores() {
        ModeloListaProfesor modelo = (ModeloListaProfesor) jListProfesores.getModel();
        modelo.setFilas(fa.obtenerProfesores());

    }

}
