/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui.formularios;

import aplicacion.AutenticacionSingleton;
import aplicacion.SesionCliente;
import aplicacion.SesionProfesor;
import aplicacion.TipoUsuario;
import gui.modelos.ModeloTablaSesionesClientes;
import gui.modelos.ModeloTablaSesionesProfesor;
import gui.auxiliares.posicionamientoVentanas;
import static gui.auxiliares.posicionamientoVentanas.centrarVentana;

import java.util.List;

import javax.swing.*;

/**
 *
 * @author alumnogreibd
 */
public final class VUsuario extends javax.swing.JFrame{

    /**
     * Creates new form VProfesor
     */
    aplicacion.FachadaAplicacion fa;
    
    public VUsuario(aplicacion.FachadaAplicacion fa) {
        this.fa=fa;
        initComponents();
        posicionamientoVentanas.centrarVentana(this);
        setSize(600, 476);
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        VAdmin = new javax.swing.JFrame();
        JPanelAdmin = new javax.swing.JPanel();
        comboSeleccionTipoUsuarioDesdeAdmin = new javax.swing.JComboBox<>();
        btnSalir1 = new java.awt.Button();
        btnClientes = new javax.swing.JButton();
        btnPersonal = new javax.swing.JButton();
        btnAulas = new javax.swing.JButton();
        btnGrupos = new javax.swing.JButton();
        btnPersonal1 = new javax.swing.JButton();
        VProfesor = new javax.swing.JFrame();
        jPanel3 = new javax.swing.JPanel();
        comboSeleccionTipoUsuarioDesdeProfesor = new javax.swing.JComboBox<>();
        btnSalir2 = new java.awt.Button();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaSesionesProfesor = new javax.swing.JTable();
        labelNombre = new javax.swing.JLabel();
        labelAula = new javax.swing.JLabel();
        jTextFieldActividadProfesor = new javax.swing.JTextField();
        jTextFieldAulaProfesor = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JLabel();
        btnBorrar = new javax.swing.JLabel();
        btnBorrar1 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jTextFieldFechaProfesor = new javax.swing.JTextField();
        jTextFieldHoraProfesor = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldDescripcionProfesor = new javax.swing.JTextField();
        JPanelCliente = new javax.swing.JPanel();
        comboSeleccionTipoUsuarioDesdeUsuario = new javax.swing.JComboBox<>();
        btnSalir = new java.awt.Button();
        txtActividad = new javax.swing.JTextField();
        txtNombreAula = new javax.swing.JTextField();
        txtFechaSesion = new javax.swing.JTextField();
        labelActividad = new javax.swing.JLabel();
        labelAulaCliente = new javax.swing.JLabel();
        jLabelFecha = new javax.swing.JLabel();
        labelHora = new javax.swing.JLabel();
        txtHora = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaSesionesCliente = new javax.swing.JTable();
        btnBuscarSesiones = new javax.swing.JButton();

        VAdmin.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        VAdmin.setTitle("Menú Principal");
        VAdmin.setMinimumSize(new java.awt.Dimension(100, 100));
        VAdmin.setName("lienzoPrincipal"); // NOI18N

        JPanelAdmin.setBackground(new java.awt.Color(53, 126, 199));
        JPanelAdmin.setPreferredSize(new java.awt.Dimension(600, 500));

        comboSeleccionTipoUsuarioDesdeAdmin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cliente", "Profesor", "Administrador" }));
        comboSeleccionTipoUsuarioDesdeAdmin.setSelectedIndex(2);
        comboSeleccionTipoUsuarioDesdeAdmin.setToolTipText("Selecciona que vista quieres usar");
        comboSeleccionTipoUsuarioDesdeAdmin.setName("comboTipoUsuario"); // NOI18N
        comboSeleccionTipoUsuarioDesdeAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboSeleccionTipoUsuarioDesdeAdminActionPerformed(evt);
            }
        });

        btnSalir1.setActionCommand("btnSalir");
        btnSalir1.setBackground(new java.awt.Color(255, 0, 0));
        btnSalir1.setLabel("Salir");
        btnSalir1.setName("btnAdminSalir"); // NOI18N
        btnSalir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalir1ActionPerformed(evt);
            }
        });

        btnClientes.setText("Gestión de Clientes");
        btnClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientesActionPerformed(evt);
            }
        });

        btnPersonal.setText("Gestion de Personal");

        btnAulas.setText("Gestion de aulas");

        btnGrupos.setText("Gestion de grupos");
        btnGrupos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGruposActionPerformed(evt);
            }
        });

        btnPersonal1.setText("Gestion de Actividades");
        btnPersonal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPersonal1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JPanelAdminLayout = new javax.swing.GroupLayout(JPanelAdmin);
        JPanelAdmin.setLayout(JPanelAdminLayout);
        JPanelAdminLayout.setHorizontalGroup(
            JPanelAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelAdminLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JPanelAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPanelAdminLayout.createSequentialGroup()
                        .addComponent(comboSeleccionTipoUsuarioDesdeAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanelAdminLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSalir1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanelAdminLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(JPanelAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnClientes, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                    .addComponent(btnAulas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 167, Short.MAX_VALUE)
                .addGroup(JPanelAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPersonal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGrupos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66))
            .addGroup(JPanelAdminLayout.createSequentialGroup()
                .addGap(208, 208, 208)
                .addComponent(btnPersonal1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JPanelAdminLayout.setVerticalGroup(
            JPanelAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelAdminLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(comboSeleccionTipoUsuarioDesdeAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addGroup(JPanelAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnPersonal1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(JPanelAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGrupos, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAulas, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addComponent(btnSalir1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(134, 134, 134))
        );

        btnSalir1.getAccessibleContext().setAccessibleDescription("Botón que sale de la apliación");
        btnPersonal1.getAccessibleContext().setAccessibleDescription("Accede al menu de gestión de actividades");

        javax.swing.GroupLayout VAdminLayout = new javax.swing.GroupLayout(VAdmin.getContentPane());
        VAdmin.getContentPane().setLayout(VAdminLayout);
        VAdminLayout.setHorizontalGroup(
            VAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPanelAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        VAdminLayout.setVerticalGroup(
            VAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPanelAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        JPanelAdmin.getAccessibleContext().setAccessibleName("JPanel administrador");
        JPanelAdmin.getAccessibleContext().setAccessibleDescription("panel que contiene los componentes de las ventanas para administradores");

        centrarVentana(VAdmin);

        VProfesor.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        VProfesor.setTitle("Menú Principal");
        VProfesor.setMinimumSize(new java.awt.Dimension(100, 100));
        VProfesor.setName("lienzoPrincipal"); // NOI18N
        VProfesor.setPreferredSize(new java.awt.Dimension(600, 500));

        jPanel3.setBackground(new java.awt.Color(53, 126, 199));
        jPanel3.setName(""); // NOI18N

        comboSeleccionTipoUsuarioDesdeProfesor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cliente", "Profesor", "Administrador" }));
        comboSeleccionTipoUsuarioDesdeProfesor.setSelectedIndex(1);
        comboSeleccionTipoUsuarioDesdeProfesor.setToolTipText("Seleccione que vista quiere ver");
        comboSeleccionTipoUsuarioDesdeProfesor.setName("comboTipoUsuario"); // NOI18N
        comboSeleccionTipoUsuarioDesdeProfesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboSeleccionTipoUsuarioDesdeProfesorActionPerformed(evt);
            }
        });

        btnSalir2.setActionCommand("btnSalir");
        btnSalir2.setBackground(new java.awt.Color(255, 0, 0));
        btnSalir2.setLabel("Salir");
        btnSalir2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalir2ActionPerformed(evt);
            }
        });

        tablaSesionesProfesor.setModel(new gui.modelos.ModeloTablaSesionesProfesor());
        jScrollPane2.setViewportView(tablaSesionesProfesor);

        labelNombre.setText("Nombre:");

        labelAula.setText("Aula:");

        jTextFieldActividadProfesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldActividadProfesorActionPerformed(evt);
            }
        });

        jTextFieldAulaProfesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAulaProfesorActionPerformed(evt);
            }
        });

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/lupa.png"))); // NOI18N
        btnBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarMouseClicked(evt);
            }
        });

        btnBorrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/goma.png"))); // NOI18N
        btnBorrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBorrarMouseClicked(evt);
            }
        });

        btnBorrar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/crear.png"))); // NOI18N
        btnBorrar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBorrar1MouseClicked(evt);
            }
        });

        jButton5.setText("Sesiones");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Alumnos");

        jTextFieldFechaProfesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFechaProfesorActionPerformed(evt);
            }
        });

        jLabel1.setText("Fecha:");

        jLabel2.setText("Hora:");

        jLabel3.setText("jLabel3");

        jLabel5.setText("Descripcion");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(comboSeleccionTipoUsuarioDesdeProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jButton5))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                            .addGap(41, 41, 41)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(labelNombre)
                                                .addComponent(jLabel1)
                                                .addComponent(jLabel5))
                                            .addGap(18, 18, 18)
                                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jTextFieldFechaProfesor, javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jTextFieldActividadProfesor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                                                .addComponent(jTextFieldDescripcionProfesor)))
                                        .addComponent(jLabel3))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                            .addComponent(jLabel2)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jTextFieldHoraProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                            .addComponent(labelAula)
                                            .addGap(18, 18, 18)
                                            .addComponent(jTextFieldAulaProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(37, 37, 37)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                            .addComponent(btnBuscar)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(btnBorrar)
                                            .addGap(18, 18, 18)
                                            .addComponent(btnBorrar1))
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                            .addGap(10, 10, 10)
                                            .addComponent(btnSalir2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(comboSeleccionTipoUsuarioDesdeProfesor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextFieldActividadProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelNombre)
                                    .addComponent(jTextFieldAulaProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelAula))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextFieldFechaProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldHoraProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnBuscar)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(btnBorrar1)
                                        .addComponent(btnBorrar)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSalir2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldDescripcionProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6)
                    .addComponent(jButton5))
                .addGap(61, 61, 61))
        );

        btnSalir2.getAccessibleContext().setAccessibleDescription("Permite salir de la aplicación");

        javax.swing.GroupLayout VProfesorLayout = new javax.swing.GroupLayout(VProfesor.getContentPane());
        VProfesor.getContentPane().setLayout(VProfesorLayout);
        VProfesorLayout.setHorizontalGroup(
            VProfesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        VProfesorLayout.setVerticalGroup(
            VProfesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        VProfesor.getAccessibleContext().setAccessibleParent(this);
        centrarVentana(VProfesor);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menú Principal");
        setMinimumSize(new java.awt.Dimension(100, 100));
        setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
        setName("lienzoPrincipal"); // NOI18N
        setPreferredSize(new java.awt.Dimension(600, 500));

        JPanelCliente.setBackground(new java.awt.Color(53, 126, 199));

        comboSeleccionTipoUsuarioDesdeUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cliente", "Profesor", "Administrador" }));
        comboSeleccionTipoUsuarioDesdeUsuario.setToolTipText("Seleccione que vista desea ver");
        comboSeleccionTipoUsuarioDesdeUsuario.setName("comboTipoUsuario"); // NOI18N
        comboSeleccionTipoUsuarioDesdeUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboSeleccionTipoUsuarioDesdeUsuarioActionPerformed(evt);
            }
        });

        btnSalir.setActionCommand("btnSalir");
        btnSalir.setBackground(new java.awt.Color(255, 0, 0));
        btnSalir.setLabel("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        txtActividad.setToolTipText("Número del grupo a buscar");
        txtActividad.setActionCommand("<Not Set>");

        txtNombreAula.setToolTipText("Aula en la que se realiza la actividad");
        txtNombreAula.setName("txtAula"); // NOI18N
        txtNombreAula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreAulaActionPerformed(evt);
            }
        });

        txtFechaSesion.setToolTipText("Introduce aquí la fecha a buscar");
        txtFechaSesion.setName("txtFecha"); // NOI18N

        labelActividad.setText("Actividad");

        labelAulaCliente.setText("Aula");

        jLabelFecha.setText("Fecha");
        jLabelFecha.setName("jLabelFecha"); // NOI18N

        labelHora.setText("Hora");

        txtHora.setToolTipText("Hora en la que se llevará a cabo la actividad");
        txtHora.setActionCommand("<Not Set>");
        txtHora.setName("txtHora"); // NOI18N
        txtHora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHoraActionPerformed(evt);
            }
        });

        tablaSesionesCliente.setModel(new gui.modelos.ModeloTablaSesionesClientes());
        jScrollPane1.setViewportView(tablaSesionesCliente);

        btnBuscarSesiones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/lupa.png"))); // NOI18N
        btnBuscarSesiones.setToolTipText("Busca futuras sesiones");
        btnBuscarSesiones.setName("btnBuscarSesiones"); // NOI18N
        btnBuscarSesiones.setOpaque(true);
        btnBuscarSesiones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarSesionesMouseClicked(evt);
            }
        });
        btnBuscarSesiones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarSesionesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JPanelClienteLayout = new javax.swing.GroupLayout(JPanelCliente);
        JPanelCliente.setLayout(JPanelClienteLayout);
        JPanelClienteLayout.setHorizontalGroup(
            JPanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JPanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanelClienteLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(JPanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, JPanelClienteLayout.createSequentialGroup()
                                .addComponent(labelHora, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtHora, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(JPanelClienteLayout.createSequentialGroup()
                                .addComponent(labelActividad, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtActividad, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)))
                        .addGap(3, 3, 3)
                        .addGroup(JPanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelFecha)
                            .addComponent(labelAulaCliente))
                        .addGap(18, 18, 18)
                        .addGroup(JPanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtNombreAula, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFechaSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43)
                        .addComponent(btnBuscarSesiones, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(139, 139, 139))
                    .addGroup(JPanelClienteLayout.createSequentialGroup()
                        .addGroup(JPanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(JPanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(JPanelClienteLayout.createSequentialGroup()
                                    .addGap(25, 25, 25)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(comboSeleccionTipoUsuarioDesdeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(39, Short.MAX_VALUE))))
        );
        JPanelClienteLayout.setVerticalGroup(
            JPanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(comboSeleccionTipoUsuarioDesdeUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(JPanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPanelClienteLayout.createSequentialGroup()
                        .addGroup(JPanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(JPanelClienteLayout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(JPanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(labelActividad)
                                    .addComponent(txtActividad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNombreAula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelAulaCliente))
                                .addGap(31, 31, 31)
                                .addComponent(labelHora))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanelClienteLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(JPanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelFecha)
                                    .addComponent(txtFechaSesion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64))
                    .addGroup(JPanelClienteLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(btnBuscarSesiones, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        comboSeleccionTipoUsuarioDesdeUsuario.getAccessibleContext().setAccessibleName("desplegableTipoAcceso");
        comboSeleccionTipoUsuarioDesdeUsuario.getAccessibleContext().setAccessibleDescription("Permite escoger el tipo de acceso");
        btnSalir.getAccessibleContext().setAccessibleDescription("Sale de la aplicación");
        txtActividad.getAccessibleContext().setAccessibleName("CampoBúsquedaGrupo");
        txtNombreAula.getAccessibleContext().setAccessibleName("CampoBúsquedaGrupo");
        txtNombreAula.getAccessibleContext().setAccessibleDescription("Número del grupo a buscar");
        txtFechaSesion.getAccessibleContext().setAccessibleName("Entrada Fecha a buscar");
        labelAulaCliente.getAccessibleContext().setAccessibleDescription("Etiqueta en la que se lee \"Aula\". Debajo se puede insertar un nombre de aula para realizar una búsqueda");
        jLabelFecha.getAccessibleContext().setAccessibleDescription("Etiqueta en la que pone fecha. Se espera la fecha a buscar debajo");
        txtHora.getAccessibleContext().setAccessibleName("HoraGrupoBuscar");
        txtHora.getAccessibleContext().setAccessibleDescription("Campo para introducir la hora a buscar");
        btnBuscarSesiones.getAccessibleContext().setAccessibleName("Boton buscar sesiones");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPanelCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPanelCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        JPanelCliente.getAccessibleContext().setAccessibleName("Panel Cliente");
        JPanelCliente.getAccessibleContext().setAccessibleDescription("Panel que contiene los componentes que verán los clientes");

        getAccessibleContext().setAccessibleDescription("Pantall del menú principal");
        getAccessibleContext().setAccessibleParent(this);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    void seleccionarPantalla(JComboBox<String> comboBox)
    {
        switch(comboBox.getSelectedIndex()){
            case 0:
                this.setVisible(true);
                VAdmin.setVisible(false);
                VProfesor.setVisible(false);
                this.pack();
                comboBox.setSelectedIndex(0);
                comboSeleccionTipoUsuarioDesdeUsuario.setSelectedIndex(0);
                comboSeleccionTipoUsuarioDesdeAdmin.setSelectedIndex(0);
                comboSeleccionTipoUsuarioDesdeProfesor.setSelectedIndex(0);
                break;

            case 1:
                this.setVisible(false);
                VAdmin.setVisible(false);
                VProfesor.setVisible(true);
                VProfesor.pack();
                comboBox.setSelectedIndex(1);
                comboSeleccionTipoUsuarioDesdeUsuario.setSelectedIndex(1);
                comboSeleccionTipoUsuarioDesdeAdmin.setSelectedIndex(1);
                comboSeleccionTipoUsuarioDesdeProfesor.setSelectedIndex(1);
                break;

            case 2:
                this.setVisible(false);
                VAdmin.setVisible(true);
                VProfesor.setVisible(false);
                VAdmin.pack();
                comboBox.setSelectedIndex(2);
                comboSeleccionTipoUsuarioDesdeUsuario.setSelectedIndex(2);
                comboSeleccionTipoUsuarioDesdeAdmin.setSelectedIndex(2);
                comboSeleccionTipoUsuarioDesdeProfesor.setSelectedIndex(2);
                break;

        }
    }
    
    private void comboSeleccionTipoUsuarioDesdeUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboSeleccionTipoUsuarioDesdeUsuarioActionPerformed
        seleccionarPantalla(comboSeleccionTipoUsuarioDesdeUsuario);
    }//GEN-LAST:event_comboSeleccionTipoUsuarioDesdeUsuarioActionPerformed

    private void comboSeleccionTipoUsuarioDesdeAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboSeleccionTipoUsuarioDesdeAdminActionPerformed
        seleccionarPantalla(comboSeleccionTipoUsuarioDesdeAdmin);
    }//GEN-LAST:event_comboSeleccionTipoUsuarioDesdeAdminActionPerformed

    private void comboSeleccionTipoUsuarioDesdeProfesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboSeleccionTipoUsuarioDesdeProfesorActionPerformed
        seleccionarPantalla(comboSeleccionTipoUsuarioDesdeProfesor);
    }//GEN-LAST:event_comboSeleccionTipoUsuarioDesdeProfesorActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // Ahora toca salir
        salidaEstandarUsuario();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnSalir2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalir2ActionPerformed
        salidaEstandarUsuario();
    }//GEN-LAST:event_btnSalir2ActionPerformed

    private void btnSalir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalir1ActionPerformed
        salidaEstandarUsuario();
    }//GEN-LAST:event_btnSalir1ActionPerformed

    private void btnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnClientesActionPerformed

    private void jTextFieldActividadProfesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldActividadProfesorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldActividadProfesorActionPerformed

    private void jTextFieldAulaProfesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAulaProfesorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAulaProfesorActionPerformed

    private void btnBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMouseClicked
        // TODO add your handling code here:
        //Profesor
        actualizarBusquedaSesionesProfesor();
    }//GEN-LAST:event_btnBuscarMouseClicked

    private void btnBorrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBorrarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBorrarMouseClicked

    private void btnBorrar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBorrar1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBorrar1MouseClicked

    private void btnBuscarSesionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarSesionesMouseClicked
        // TODO add your handling code here:
        actualizarBusquedaSesiones();
    }//GEN-LAST:event_btnBuscarSesionesMouseClicked

    private void btnBuscarSesionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarSesionesActionPerformed
        actualizarBusquedaSesiones();
        
    }//GEN-LAST:event_btnBuscarSesionesActionPerformed

    private void txtNombreAulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreAulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreAulaActionPerformed

    private void txtHoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHoraActionPerformed

    private void btnGruposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGruposActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGruposActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTextFieldFechaProfesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFechaProfesorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFechaProfesorActionPerformed

    private void btnPersonal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPersonal1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPersonal1ActionPerformed




    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPanelAdmin;
    private javax.swing.JPanel JPanelCliente;
    private javax.swing.JFrame VAdmin;
    private javax.swing.JFrame VProfesor;
    private javax.swing.JButton btnAulas;
    private javax.swing.JLabel btnBorrar;
    private javax.swing.JLabel btnBorrar1;
    private javax.swing.JLabel btnBuscar;
    private javax.swing.JButton btnBuscarSesiones;
    private javax.swing.JButton btnClientes;
    private javax.swing.JButton btnGrupos;
    private javax.swing.JButton btnPersonal;
    private javax.swing.JButton btnPersonal1;
    private java.awt.Button btnSalir;
    private java.awt.Button btnSalir1;
    private java.awt.Button btnSalir2;
    private javax.swing.JComboBox<String> comboSeleccionTipoUsuarioDesdeAdmin;
    private javax.swing.JComboBox<String> comboSeleccionTipoUsuarioDesdeProfesor;
    private javax.swing.JComboBox<String> comboSeleccionTipoUsuarioDesdeUsuario;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelFecha;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextFieldActividadProfesor;
    private javax.swing.JTextField jTextFieldAulaProfesor;
    private javax.swing.JTextField jTextFieldDescripcionProfesor;
    private javax.swing.JTextField jTextFieldFechaProfesor;
    private javax.swing.JTextField jTextFieldHoraProfesor;
    private javax.swing.JLabel labelActividad;
    private javax.swing.JLabel labelAula;
    private javax.swing.JLabel labelAulaCliente;
    private javax.swing.JLabel labelHora;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JTable tablaSesionesCliente;
    private javax.swing.JTable tablaSesionesProfesor;
    private javax.swing.JTextField txtActividad;
    private javax.swing.JTextField txtFechaSesion;
    private javax.swing.JTextField txtHora;
    private javax.swing.JTextField txtNombreAula;
    // End of variables declaration//GEN-END:variables

    public void actualizarNivelAcceso(TipoUsuario nivelAcceso)
    {
        switch(nivelAcceso)
        {
            case Cliente:
                comboSeleccionTipoUsuarioDesdeUsuario.setSelectedIndex(0);
                comboSeleccionTipoUsuarioDesdeUsuario.setModel(new DefaultComboBoxModel<>(new String[] { "Cliente" }));
                comboSeleccionTipoUsuarioDesdeAdmin.setModel(new DefaultComboBoxModel<>(new String[] { "Cliente" }));
                comboSeleccionTipoUsuarioDesdeProfesor.setModel(new DefaultComboBoxModel<>(new String[] { "Cliente" }));
                break;
            case Administrador:
                // DO - NOTHING
                // No hay que hacer nada, ya que el administrador puede ver todas las opciones
                break;
            case Profesor:
                comboSeleccionTipoUsuarioDesdeUsuario.setSelectedIndex(0);
                comboSeleccionTipoUsuarioDesdeUsuario.setModel(new DefaultComboBoxModel<>(new String[] {"Cliente", "Profesor" }));
                comboSeleccionTipoUsuarioDesdeProfesor.setModel(new DefaultComboBoxModel<>(new String[] {"Cliente", "Profesor" }));
                break;
        }
    }

    private void salidaEstandarUsuario() {
        this.dispose();
        System.out.println("INFO: Saliendo de la aplicación. Nada que reportar.");
        System.exit(0);
    }

    void actualizarBusquedaSesiones()
    {

        String nickname = AutenticacionSingleton.getInstance().getNickname();
        ModeloTablaSesionesClientes m = (ModeloTablaSesionesClientes) tablaSesionesCliente.getModel();
        List <SesionCliente> sesiones = fa.obtenerSesionesCliente(nickname, txtActividad.getText(), txtNombreAula.getText(), txtFechaSesion.getText(), txtHora.getText());
        m.setFilas(sesiones);
    }
    
    void actualizarBusquedaSesionesProfesor()
    {
        String hora = jTextFieldHoraProfesor.getText();
        if(!hora.isBlank() && !comprobarFormatoHora(hora))
        {
            JOptionPane.showMessageDialog(this, "El formato de la hora no es correcto. Por favor, introduzca una hora en formato HH:MM.\nSi es correcto, comprueba las fechas introducidas", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        String fechaBruta = jTextFieldFechaProfesor.getText();
        String fecha = "";
        if(!fechaBruta.isBlank() && !comprobarFormatoFecha(fechaBruta,true))
        {
            JOptionPane.showMessageDialog(this, "El formato de la fecha no es correcto. Por favor, introduzca una fecha en formato YYYY-MM-DD", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if(!fechaBruta.isBlank())
        {
            fecha = procesarFecha(fechaBruta);
            System.out.println("[DEBUG] Fecha procesada: " + fecha);
        }
        
        String nickname = AutenticacionSingleton.getInstance().getNickname();
        ModeloTablaSesionesProfesor m = (ModeloTablaSesionesProfesor) tablaSesionesProfesor.getModel();
        List <SesionProfesor> sesiones = fa.obtenerSesionesProfesor(nickname, jTextFieldActividadProfesor.getText(), jTextFieldAulaProfesor.getText(), fecha, hora, jTextFieldDescripcionProfesor.getText());
        m.setFilas(sesiones);
    }

    boolean comprobarFormatoHora(String horaAcomprobar)
    {
        return horaAcomprobar.matches("(([01]?[0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9])|(([01]?[0-9]|2[0-3]):[0-5][0-9])");
    }

    boolean comprobarFormatoFecha(String fecha, boolean modo)
    {
//        return fecha.matches("([0-9]{4})-([01]?[0-9])-([0-9]{2})");
        //formato español dd-mm-yyyy (0-31, 0-12, 0-9999)
        if(modo)
        {
            return fecha.matches("([0-9]{2})-([01]?[0-9]|1[0-2])-([0-9]{4})");
        }
        else
        {
            return fecha.matches("([0-9]{4})-([01]?[0-9]|1[0-2])-([0-9]{2})");
        }
//        return fecha.matches("([0-9]{4})-([01]?[0-9]|1[0-2])-([0-9]{2})");

    }

    String procesarFecha(String fecha)
    {
        String[] fechaDividida = fecha.split("-");
        return fechaDividida[2] + "-" + fechaDividida[1] + "-" + fechaDividida[0];
    }

}
